apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Application Release with manifest
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
jobs:
  pre-prod:
    environment: pre-prod
    steps:
      - name: Deploy App6-Frontend to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App6-Frontend']['App6-Frontend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App6-Frontend']['App6-Frontend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App6-Frontend']['App6-Frontend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App6-Frontend']['App6-Frontend'].digest }}
          target-environment: pre-prod
          name: App6-Frontend

      - name: Deploy App6-Backend to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App6-Backend']['App6-Backend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App6-Backend']['App6-Backend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App6-Backend']['App6-Backend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App6-Backend']['App6-Backend'].digest }}
          target-environment: pre-prod
          name: App6-Backend

      - name: Deploy App6-APIs to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App6-APIs']['App6-APIs'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App6-APIs']['App6-APIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['App6-APIs']['App6-APIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App6-APIs']['App6-APIs'].digest }}
          target-environment: pre-prod
          name: App6-APIs
  prod:
    needs: pre-prod
    environment: prod
    steps:
      - name: Deploy App6-Frontend to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App6-Frontend']['App6-Frontend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App6-Frontend']['App6-Frontend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App6-Frontend']['App6-Frontend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App6-Frontend']['App6-Frontend'].digest }}
          target-environment: prod
          name: App6-Frontend

      - name: Deploy App6-Backend to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App6-Backend']['App6-Backend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App6-Backend']['App6-Backend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App6-Backend']['App6-Backend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App6-Backend']['App6-Backend'].digest }}
          target-environment: prod
          name: App6-Backend

      - name: Deploy App6-APIs to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App6-APIs']['App6-APIs'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App6-APIs']['App6-APIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['App6-APIs']['App6-APIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App6-APIs']['App6-APIs'].digest }}
          target-environment: prod
          name: App6-APIs
